### ISSUE TITLE
 Auto install not work, it also need wizard [prestashop]

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/docker-library#141]
**Describe the bug**

```
root@iZbp16qbwx8qqcgq7ab0dhZ:~/docker-prestashop# docker logs prestashop

* Reapplying PrestaShop files for enabled volumes ...
/tmp/docker_run.sh: 15: [: Illegal number: false

* Installing PrestaShop, this may take a while ...
Field http_host is not valid

* Almost ! Starting Apache now

AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 192.168.144.3. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 192.168.144.3. Set the 'ServerName' directive globally to suppress this message
[Sat Aug 14 10:05:24.954275 2021] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.10 (Debian) configured -- resuming normal operations
[Sat Aug 14 10:05:24.954327 2021] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
47.75.113.190 - - [14/Aug/2021:10:05:45 +0000] "GET / HTTP/1.1" 302 189 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36"
[Sat Aug 14 10:06:17.532390 2021] [:error] [pid 23] [client 47.75.113.190:50214] PHP Warning:  file_put_contents(/var/www/html/app/cache/prod/cacert.pem): failed to open stream: No such file or directory in /var/www/html/classes/Tools.php on line 1898
47.75.113.190 - - [14/Aug/2021:10:05:45 +0000] "GET /install/ HTTP/1.1" 200 3371 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36"

```

**Comment by qiaofeng1227** [comment]
```
  prestashop:
    image: prestashop/prestashop:${APP_VERSION}
    container_name: ${APP_NAME}
    ports:
      - ${APP_PORT}:80
    volumes:
      - prestashop:/var/www/html
    environment:
      - PS_DEMO_MODE=1
      - PS_INSTALL_AUTO=1
      - PS_DOMAIN=${APP_SITE_URL}
      - PS_HANDLE_DYNAMIC_DOMAIN=0
      - PS_COUNTRY=GB
      - PS_LANGUAGE=en
      - DB_SERVER=mysql
      - DB_USER=${DB_MYSQL_USER}
      - DB_PASSWD=${DB_MYSQL_PASSWORD}
      - DB_PREFIX=ps_
      - ADMIN_MAIL=${EMAIL}
      - ADMIN_PASSWD=${APP_PASSWORD}
```
