### ISSUE TITLE
 几个使用问题  enhancement [rainbond]

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/docker-library#144]
**What type of your feature request?**  

1. 用户通过管理控制台输入密码是开始配置时设置的，这个密码不通过页面，如何通过脚本修改并生效（暂时不处理）
2. 建立集群时设置的公网和内网IP如何通过脚本修改并生效（？）
3. 服务器重启后，之前我创建的应用tomcat容器不是重新启动，而是退出了老的tomcat容器，有创建了一个新的tomcat容器。应用的数据无法保存 (有状态？无状态？)
4. 自己创建的应用能通过 生成的url外网访问，但是开通外网端口后，无法通过ip+端口访问（内网域名+外网域名）
5. 持久存储的目录（？）
6. 重启后有状态应用没有自动重启？
7. 根据dockercompose创建组件失败？

**Comment by qiaofeng1227** [comment]
k8s的存储通过nfs来管理：目录路径/opt/rainbond/data/nfs

**Comment by qiaofeng1227** [comment]
直接从菜单栏创建组件可以选择dockercompose

![image](https://user-images.githubusercontent.com/43192516/190110927-4ec7de8e-da7d-460d-b6f2-81358002e4f3.png)

![image](https://user-images.githubusercontent.com/43192516/190111877-42c21245-467d-46c9-b9dc-0b7bc2e385ec.png)
```
version: "3.8"
services:
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    container_name: pgadmin
    ports:
      - "9091:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=uQ8E1wVTzG8SOk3
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0

networks:
  default:
    name: websoft9
```
