### ISSUE TITLE
 Mount configuration file[redmine]

### ISSUE THREAD

**Issue by laozhou0731** [Websoft9/docker-library#146]
**What type of your feature request?**  

- [ ] Add new features
- [x] Improve current features

The correct way to mount the configuration file
![image](https://user-images.githubusercontent.com/62225175/183863469-b9f805e9-998f-4f33-b5f9-60b0177a50d1.png)

**Comment by laozhou0731** [comment]
Building a new configuration file configuration.yml file from existing configuration.yml.example file, Redmine works fine.

![image](https://user-images.githubusercontent.com/62225175/183864267-5e4a3366-d786-4c8a-9761-c60fb07dc572.png)

**Comment by laozhou0731** [comment]
**Verified and reliable configuration**

```
production:
  delivery_method: :smtp
  smtp_settings:
    address: smtp.exmail.qq.com
    port: 465
    ssl: true
    enable_starttls_auto: true
    domain: websoft9.com
    authentication: :login
    user_name: help@websoft9.com
    password: ******
```
