### ISSUE TITLE
Image build and push to Dockerhub automaticlly [template]

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/docker-library#184]
**What type of your feature request?**  

```
name: Docker Build And Push To Docker Hub

on:
  push:
    branches: [ main ]
    paths: 
       - 'Dockerfile'
jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: websoft9dev/vtiger
          tags: v7.4, latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
```
