### ISSUE TITLE
将共通挂载放入描点定义区 for [runtime]

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/docker-library#216]
```
x-java-defaults: &java_defaults
  entrypoint: bash -c "cat /opt/config/java/service.sh > /cmd.sh && chmod +x /cmd.sh && /cmd.sh"
  working_dir: /data/apps
  environment:
      - JAVA_APP=${JAVA_APP}
      
services:

  java19:
    container_name: java19
    restart: unless-stopped
    build:
      context: src
      dockerfile: Dockerfile.java
      args:
        - JDK_VERSION=19
    volumes: 
      - java19:/data/apps
      - ./config/java:/opt/config/java      
    <<: *java_defaults
  java18:
    container_name: java18
    restart: unless-stopped
    build:
      context: src
      dockerfile: Dockerfile.java
      args:
        - JDK_VERSION=18
    volumes: 
      - java18:/data/apps
      - ./config/java:/opt/config/java
    <<: *java_defaults
```

refer to:
https://yaml.org/type/merge.html
https://learnxinyminutes.com/docs/yaml/
