### ISSUE TITLE
【专题】优化 Docker 日志方案

### ISSUE THREAD

**Issue by laozhou0731** [Websoft9/docker-library#240]
Docker 容器在运行过程中会产生大量日志文件，占用磁盘资源，导致下列问题：

- 数据库起不来
- 应用程序无法上传文件
......

期望：

- 在容器或 Docker 全局层面对日志大小进行控制
- 对日志的查看更加方便

参考：

- [Docker Official Documentation ](https://docs.docker.com/config/containers/logging/configure/)
- [Docker容器日志设置、查看与清理](https://blog.csdn.net/yjk13703623757/article/details/80283729)

**Comment by chendelin1982** [comment]
以 WordPress 为例，它的日志位置为：
```
docker inspect --format='{{.LogPath}}' CONTAINER_NAME
```

然后 echo ""  到上述位置即可

**Comment by chendelin1982** [comment]
也可以往 docker-compose 文件增加：
```
  wordpress:
    image: wordpress:${APP_VERSION}
    container_name: ${APP_NAME}
    restart: always
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: 10m
```
