### ISSUE TITLE
Github aciton 自动更新apps的variables.json  - pay ¥100

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/docker-library#245]
触发条件：
1.  template/variables.json main分支发生变化
2. 更新所有apps/*/variables.json
3. 当 template/variables.json 中有曾加或删除 某个json项目，apps/*/variables.json需要对应 增加和删除 
4. 对于apps/*/variables.json 和 template/variables.json都有的项目，需要apps/*/variables.json 的项目保持不变

**Comment by xyt52** [comment]
meta.yml
```
name: Template README by variables.json

on: 
# repository_dispatch:
  push:
    branches: [ main ]
    paths: 
      - 'template/variables.json'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      name: Check out code  
      
    - name: npm install jinjia2-cli
      run: |
       wget -N https://raw.githubusercontent.com/Websoft9/docker-library/main/template/variables.json -O template_variables.json
       pip install jinja2-cli
       
    - name: update all variables.json
      run: |
        files=$(ls apps/)
        for file in $files;do
            echo $file
            cp -r apps/$file/variables.json  variables.json
            jinja2 template_variables.json variables.json > apps/$file/variables.json
          fi
        done     
       
    - name: push variables.json  
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Templating variables.json
```
variables.json文件格式如下
```
{
  "name": "{{name}}",
  "trademark": "{{trademark}}",
  "fork_url": "https://github.com/docker-library/apps/{{name}}",
  "version": "{{version}}",
  "requirements":{
    "cpu": "{{requirements.cpu}}",
    "memory": "{{requirements.memory}}",
    "disk": "{{requirements.disk}}",
    "url": "https://github.com/docker-library/apps/{{name}}"
  }
}
```
不足之处：
如果``` apps/$file/variables.json```里比``` template/variables.json```里的key多，更新后，多余的key会被覆盖

目前的尝试，主要问题在于，不能直观地发现，文档具体更新了哪里，所以不能有针对地对``` apps/$file/variables.json```进行处理
