### ISSUE TITLE
complete docker compose for [prometheus]

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/docker-library#354]
**What type of your feature request?**  

- [x] create docker-compose.yml and testing OK
- [x] credentials?
      https://prometheus.io/docs/guides/basic-auth/#hashing-a-password
- [x] more environment
- [x] connect with alert and pushgateway?

**Comment by qiaofeng1227** [comment]
prometheus.yml
```
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - 'alertmanager:9093'
```

alertmanager.yml
```
global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'

receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://example.com/'
```
