### ISSUE TITLE
add vm.max_map_count item at config.ini or system.ini

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/docker-library#432]
**Describe the bug**

vm.max_map_count 是 Linux 内核参数，它定义了一个进程可能拥有的最大内存映射区域数量。这个参数的默认值可能因系统而异，但在许多系统上，它的默认值是 65530。

But some application need more large value

- [ ] Elastic 
- [ ] opensearch

**Comment by chendelin1982** [comment]
use Busybox container to modify for temp solution
```
  busybox:
    image: busybox
    command: /bin/sh -c "sysctl -w vm.max_map_count=262144"
    privileged: true
```
