### ISSUE TITLE
appflowy is a incomplete apps

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/docker-library#438]
```
version: '3.8'

services:
  appflowy:
  env_file: .env


networks:
  default:
    name: ${W9_NETWORK}
    external: true

volumes:
  appflowy:
```
