### ISSUE TITLE
create new compose for [bytebase]

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/docker-library#566]
**What type of your feature request?**  

docs: https://www.bytebase.com/docs/get-started/self-host/#docker

**Comment by chendelin1982** [comment]
初始化设置通过cmd: https://www.bytebase.com/docs/reference/command-line/

**Comment by qiaofeng1227** [comment]
```
services:
  bytebase:
    image: $W9_REPO:$W9_VERSION
    container_name: $W9_ID
    #command: ["--backup-bucket", "your-bucket-name"]
    env_file:
      - .env
    restart: unless-stopped
```

**Comment by chendelin1982** [comment]
> ```
> services:
>   bytebase:
>     image: $W9_REPO:$W9_VERSION
>     container_name: $W9_ID
>     #command: ["--backup-bucket", "your-bucket-name"]
>     env_file:
>       - .env
>     restart: unless-stopped
> ```

provide refer official docs

**Comment by qiaofeng1227** [comment]
https://www.bytebase.com/docs/get-started/self-host/

```
mkdir ~/volumes
colima start --mount ~/volumes:w
docker run --init \
  --name bytebase \
  --restart always \
  --publish 80:8080 \
  --volume ~/.bytebase/data:/var/opt/bytebase bytebase/bytebase:2.13.2 \
  --data /var/opt/bytebase \
  --external-url https://bytebase.example.com \
  --port 8080
```
将docker命令转换成docker-compose.yml
```
version: '3.8'

services:
  bytebase:
    image: bytebase/bytebase:2.13.2
    container_name: bytebase
    restart: always
    ports:
      - "80:8080"
    volumes:
      - "~/.bytebase/data:/var/opt/bytebase"
    command:
      - "--data=/var/opt/bytebase"
      - "--external-url=https://bytebase.example.com"
      - "--port=8080"


```
