### ISSUE TITLE
cpu and memory limit at docker-compose

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/docker-library#572]
**What type of your feature request?**  

- cpu_percent: 50 ?  (核 or 多路)

**Comment by qiaofeng1227** [comment]
https://docs.docker.com/compose/compose-file/

**Comment by qiaofeng1227** [comment]
memory limit has not parcent parameter

**Comment by qiaofeng1227** [comment]
```
services:
  testservice:
    image: $W9_REPO:$W9_VERSION
    container_name: $W9_ID
    restart: unless-stopped
    cpu_percent: 60
    mem_limit: 8g
```
