### ISSUE TITLE
Elasticsearch 502 Bad Gateway

### ISSUE THREAD

**Issue by wildechair** [Websoft9/docker-library#602]
![image](https://github.com/Websoft9/docker-library/assets/105709702/2495e3cb-a98d-4887-bcbd-a01b69d7a913)

![image](https://github.com/Websoft9/docker-library/assets/105709702/7f296db0-b2b6-48ef-8dc2-b6b1c88c3df8)

![image](https://github.com/Websoft9/docker-library/assets/105709702/22e3889e-fa97-4d9b-a954-f798d85c2b07)

![image](https://github.com/Websoft9/docker-library/assets/105709702/30d8a9dd-c435-4ad1-97e8-34fc1835ad8e)

**Comment by qiaofeng1227** [comment]
out of memory ：
```
    cpu_percent: 80
    mem_limit: 4g
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      nproc:
        soft: 4096
        hard: 4096
```
