### ISSUE TITLE
initial wizard after install at appstore error for [kodcloud]

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/docker-library#608]
**Describe the bug**

lastest version, when confirm initial wizard first step error, db password zb1ZCz65#IT!P9j4
```
出错了! (warning!)
method_exists(): Argument #1 ($object_or_class) must be of type object|string, null given
系统错误 (install.index.save)
bin/data.bin[2] method_exists(0,1)
bin/data.bin[2]
[Linux 5.14.0-362.18.1.el9_3.0.1.x86_64/8.2.16/mysqli/1.49.10]
```

**Comment by chendelin1982** [comment]
v1.4505 is good

**Comment by qiaofeng1227** [comment]
[目前最新版本是1.49](https://github.com/kalcaddle/kodbox), latest不是对应最新release版本。
为了让其正常运行，docker-compose需要用最新的。
```
# image: https://hub.docker.com/r/kodcloud/kodbox

version: "3.8"

services:
  mariadb:
    image: mariadb:$W9_DB_VERSION
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    container_name: $W9_ID-mariadb
    environment:
      - "TZ=Asia/Shanghai"
      - "MYSQL_DATABASE=$W9_ID"
      - "MYSQL_USER=$W9_ID"
      - "MYSQL_PASSWORD=$W9_POWER_PASSWORD"
      - "MYSQL_ROOT_PASSWORD=$W9_POWER_PASSWORD"
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql

  kodbox:
    image: $W9_REPO:$W9_VERSION
    container_name: $W9_ID
    ports:
      - $W9_HTTP_PORT_SET:$W9_HTTP_PORT
    volumes:
      - kodbox:/var/www/html
    environment:
      - "MYSQL_HOST=$W9_ID-mariadb"
      - "MYSQL_DATABASE=$W9_ID"
      - "MYSQL_USER=$W9_ID"
      - "MYSQL_PASSWORD=$W9_POWER_PASSWORD"
      - "REDIS_HOST=$W9_ID-redis"
    env_file: .env
    restart: always

  redis:
    image: redis:alpine
    container_name: $W9_ID-redis
    restart: always

volumes:
  kodbox:
  mysql_data:

networks:
  default:
    name: $W9_NETWORK
    external: true
```
.env
```
# https://hub.docker.com/r/kodcloud/kodbox
# must use 4four decimal version number
W9_VERSION=1.49
W9_DIST=community
W9_REPO=kodcloud/kodbox

W9_POWER_PASSWORD=uQ8E1wVTzG8SOk3!

#### --  Not allowed to edit below environments when recreate app based on existing data  -- ####
W9_ID=kodbox
W9_DB_EXPOSE="mariadb"
W9_DB_VERSION="10.6"
W9_HTTP_PORT=80
W9_HTTP_PORT_SET=9002
W9_URL=internet_ip
W9_NETWORK=websoft9
```
