### ISSUE TITLE
complete docker-compose.yml for [Laravel]

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/docker-library#614]
**What type of your feature request?**  

- [ ] official architecture research  
   - [requirement](https://laravel.com/docs/12.x/deployment#server-requirements) 
   - webserver: [frankenphp](https://laravel.com/docs/12.x/deployment#frankenphp)
   - [.env](https://github.com/laravel/laravel/blob/12.x/.env.example) file that exists at the root of your Laravel application for configuration
   - [permmison](https://laravel.com/docs/12.x/deployment#directory-permissions)
   - `php artisan` commad at app directory
   - `composer create-project --prefer-dist laravel/laravel project-name` create Lavarel app
   - have `.env` file by default when composer create app
   - database/migrations have db file, use `php artisan migrate` for initial
   - [fronted vs backend](https://laravel.com/docs/12.x/frontend#using-react-or-vue)
   - Livewire
- [ ] test offcial docker
- [ ] complete standardized expression
- [ ] developer test and running
- [ ] specials and refers at notes.md/.env/docker-compose.yml
- [ ] contentful
- [ ] test at Appstore and nginx proxy testing
- [ ] docs
- [ ] siteurl or baseurl
- [ ] more environments from
- [ ] connetion URI
- [ ] ports
- [ ] credentials environment
- [ ] i18n
- [ ] other

**Comment by qiaofeng1227** [comment]
1. use php runtime
```
composer create-project --prefer-dist laravel/laravel myapp
cd myapp && php artisan serve --host=0.0.0.0 --port=8080
```
3.

**Comment by qiaofeng1227** [comment]
Laravel FrameWork project have not 【Laravel package】in source.
It installed by two way:

```
git clone https://github.com/akaunting/akaunting.git
composer install
```
example project: https://github.com/akaunting/akaunting

**Comment by chendelin1982** [comment]
image: https://github.com/laravel-fans/laravel-docker/blob/main/src/stubs/Dockerfile

**Comment by qiaofeng1227** [comment]
```
version: '3.8'

services:
  laravel:
    image: laravelfans/laravel:latest
    container_name: laravel
    restart: unless-stopped
    ports:
      - '8000:80'
    environment:
      - APP_KEY=base64:L+3avOYCfuq8nnDpHs74+5Et3sx27TssucHQIyqfpDY=
      - APP_ENV=local
      - DB_CONNECTION=sqlite
    volumes:
      - 'data:/var/www/laravel'

networks:
  default:
    name: websoft9
    external: true

volumes:
  data:
```
![image](https://github.com/Websoft9/docker-library/assets/43192516/63ba8967-419b-4042-a199-99b1bacd35bb)
