### ISSUE TITLE
cannot connect db for gitea

### ISSUE THREAD

**Issue by yuanssssss** [Websoft9/docker-library#642]
**Describe the bug**

After installing the app in the websoft9 app store, 
it does not initialize with the given data and the mysql container keeps restarting, 
here is a screenshot of the bug
![image](https://github.com/user-attachments/assets/50213aff-1841-4fdd-9439-2ef874e2f874)

## Bug source

- [ ] Bugs from mysql container

**Comment by qiaofeng1227** [comment]
delete command
``` 
 mysql:
    image: mysql:$W9_DB_VERSION
    container_name: ${W9_ID}-mysql
    #command: --default-authentication-plugin=mysql_native_password    
    environment:
      MYSQL_ROOT_PASSWORD: ${W9_POWER_PASSWORD}
      MYSQL_DATABASE: ${W9_ID}
```
