### ISSUE TITLE
complete docker-compose.yml for [gitness] ￥50

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/docker-library#666]
**What type of your feature request?**  

- [x] official architecture research
- [x] test offcial docker
- [x] complete standardized expression
- [x] developer test and running
- [x] specials and refers at notes.md/.env/docker-compose.yml
- [x] contentful
- [x] test at Appstore and nginx proxy testing
- [x] docs
- [x] siteurl or baseurl
- [x] more environments from or configuration file
- [x] connetion URI
- [x] ports
- [x] credentials environment
- [x] i18n
- [x] other

**Comment by qiaofeng1227** [comment]
https://docs.gitness.com/

**Comment by qiaofeng1227** [comment]
```
version: '3.8'

services:
  gitness:
    image: harness/gitness
    container_name: gitness
    restart: always
    environment:
      - GITNESS_PRINCIPAL_ADMIN_EMAIL=mail@example.com
      - GITNESS_PRINCIPAL_ADMIN_PASSWORD=websoft9
      - GITNESS_USER_SIGNUP_ENABLED=false
      - GITNESS_CI_CONTAINER_NETWORKS=websoft9
    privileged: true
    ports:
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/gitness:/data

networks:
  default:
    name: websoft9

```
