### ISSUE TITLE
Why set hostname with domai... [gitlab]

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/docker-library#75]
```
  gitlab:
    image: gitlab/gitlab-$APP_EDITION:$APP_VERSION
    container_name: "$APP_NAME"
    hostname: "$APP_URL"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # external_url 'http://$APP_URL'
        gitlab_rails['gitlab_shell_ssh_port'] = 22
        # Add any other gitlab.rb configuration here, each on its own line
        # other
    shm_size: '256m'
    restart: always
    ports:
      - '${APP_HTTP_PORT}:80'
      - '23:22'
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
```
