### ISSUE TITLE
Env Knowage username and pa...[knowage]

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/docker-library#91]
**What type of your feature request?**  

refer to :

```
init_docker:
  knowage:
    db: mariadb
    db_name: knowage
    db_username: knowage
    db_password: "123456"
    admin_username: biadmin
    admin_password: "biadmin"
    service_after: "docker.service"
    compose_path: "/data/wwwroot/knowage/docker-compose.yml"
    compose_commands:
      - cd /data/wwwroot/knowage
      - sudo sed -i "s/123456/$new_password/g" /data/wwwroot/knowage/.env 
    volumes:
      - /data/wwwroot/knowage/volumes
    commands:
      - sudo docker exec -i knowage-server bash -c 'sed -i "s/password=\"biadmin\"/password=\"'$new_password'\"/g" /home/knowage/apache-tomcat/webapps/knowage/WEB-INF/conf/config/internal_profiling.xml'
      - sudo docker exec -i knowage-server bash -c 'sed -i "s/password=\"biadmin\"/password=\"'$new_password'\"/g" /home/knowage/apache-tomcat/webapps/knowage/WEB-INF/conf/webapp/authorizations.xml'
      - sudo mysql -uroot -p$new_password -h 127.0.0.1 knowage -e "DELETE FROM knowage.SBI_USER;"
      - sudo docker restart knowage-server
      - sudo echo -e "\e[1;31m Password initialization takes about 3-5 minutes, please wait... \e[0m" |tee -a /credentials/password.txt
```
